# coding: utf-8

"""
    Proxmox

    Proxmox VPS provider  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: webmaster@listes.minet.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_dns(self):
        """Test case for create_dns

        create dns entry  # noqa: E501
        """
        pass

    def test_create_vm(self):
        """Test case for create_vm

        create vm  # noqa: E501
        """
        pass

    def test_delete_dns_id(self):
        """Test case for delete_dns_id

        delete dns entry by id  # noqa: E501
        """
        pass

    def test_delete_vm_id(self):
        """Test case for delete_vm_id

        delete vm by id  # noqa: E501
        """
        pass

    def test_get_dns(self):
        """Test case for get_dns

        get all user's dns entries  # noqa: E501
        """
        pass

    def test_get_dns_id(self):
        """Test case for get_dns_id

        get a dns entry by id  # noqa: E501
        """
        pass

    def test_get_historyip(self):
        """Test case for get_historyip

        get the ip history of a vm  # noqa: E501
        """
        pass

    def test_get_historyipall(self):
        """Test case for get_historyipall

        get the ip history of all the vm  # noqa: E501
        """
        pass

    def test_get_vm(self):
        """Test case for get_vm

        get all user vms  # noqa: E501
        """
        pass

    def test_get_vm_id(self):
        """Test case for get_vm_id

        get a vm by id  # noqa: E501
        """
        pass

    def test_is_cotisation_uptodate(self):
        """Test case for is_cotisation_uptodate

        check is the cotisation is up to date for a user  # noqa: E501
        """
        pass

    def test_patch_vm(self):
        """Test case for patch_vm

        update a vm  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
