# coding: utf-8

"""
    Proxmox

    Proxmox VPS provider  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: webmaster@listes.minet.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.dns_entry_item import DnsEntryItem  # noqa: E501
from swagger_client.rest import ApiException


class TestDnsEntryItem(unittest.TestCase):
    """DnsEntryItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDnsEntryItem(self):
        """Test DnsEntryItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.dns_entry_item.DnsEntryItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
