# coding: utf-8

# flake8: noqa
"""
    Proxmox

    Proxmox VPS provider  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: webmaster@listes.minet.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.dns_entry_item import DnsEntryItem
from swagger_client.models.dns_item import DnsItem
from swagger_client.models.history_id_item import HistoryIdItem
from swagger_client.models.vm_id_item import VmIdItem
from swagger_client.models.vm_item import VmItem
