name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r backend/requirements.txt
        pip install -r backend/test-requirements.txt
    - name: Analysing the code with pylint
      env: 
        KEYRING_DNS_SECRET: ${{ secrets.KEYRING_DNS_SECRET }}
        PROXMOX_API_KEY_NAME: ${{ secrets.PROXMOX_API_KEY_NAME }}
        PROXMOX_API_KEY: ${{ secrets.PROXMOX_API_KEY }}
        PROXMOX_BACK_DB_DEV: ${{ secrets.PROXMOX_BACK_DB_DEV }}
        ADH6_API_KEY: ${{ secrets.ADH6_API_KEY }}
      run: |
        cd backend/
        export PYTHONPATH=$(pwd)
        export ENVIRONMENT='TEST'
        pytest --cov=proxmox_api --cov-report term-missing --cov-report xml:./coverage_out_report.xml --junitxml=report.xml
